package middleware

import (
	"encoding/hex"
	"net/http"
	"sync"
	"uuid"

	"github.com/Suhaibinator/SRouter/pkg/common"
	"github.com/Suhaibinator/SRouter/pkg/scontext"
)

// IDGenerator precomputes UUIDv7 trace IDs in a replenished buffer.
type IDGenerator struct {
	idChan   chan string
	size     int
	initOnce sync.Once
	stop     chan struct{}
	stopOnce sync.Once
}

// NewIDGenerator creates an ID generator and starts its background filler.
// bufferSize is the number of IDs retained for request-path use and must not be
// negative.
func NewIDGenerator(bufferSize int) *IDGenerator {
	g := &IDGenerator{
		idChan: make(chan string, bufferSize),
		size:   bufferSize,
		stop:   make(chan struct{}),
	}
	g.init()
	return g
}

// init starts the background goroutine that fills the channel with UUIDs
func (g *IDGenerator) init() {
	g.initOnce.Do(func() {
		// First fill the channel
		for range g.size {
			g.idChan <- generateUUID()
		}

		// Then start the background worker to keep it filled. A blocking send
		// parks the goroutine for free while the buffer is full (no polling)
		// and resumes the instant a consumer takes an ID.
		go func() {
			for {
				select {
				case <-g.stop:
					return
				case g.idChan <- generateUUID():
					// Successfully added a new UUID; loop to top up again.
				}
			}
		}()
	})
}

// Stop signals the background ID generator goroutine to exit.
// This should be called when shutting down the router to ensure
// clean termination. It's safe to call Stop multiple times.
func (g *IDGenerator) Stop() {
	g.stopOnce.Do(func() {
		close(g.stop)
	})
}

func generateUUID() string {
	id := uuid.NewV7()
	return hex.EncodeToString(id[:])
}

// GenerateTraceID returns a new trace ID without requiring a buffered ID
// generator. It is primarily useful for low-volume paths that must always be
// correlated, such as error handling when request-wide tracing is disabled.
func GenerateTraceID() string {
	return generateUUID()
}

// GetID returns a precomputed UUID from the buffer channel.
// This method blocks if the buffer is empty, waiting until a new ID
// is generated by the background goroutine. In normal operation,
// the buffer should never be empty if sized appropriately for your
// traffic patterns. Use GetIDNonBlocking for non-blocking behavior.
func (g *IDGenerator) GetID() string {
	return <-g.idChan
}

// GetIDNonBlocking attempts to get a precomputed UUID without blocking.
// If the buffer is empty, it generates a new UUID immediately in the
// calling goroutine. This ensures requests are never delayed waiting
// for an ID, even during extreme traffic spikes that exhaust the buffer.
// This is the preferred method for request-path ID generation.
func (g *IDGenerator) GetIDNonBlocking() string {
	select {
	case id := <-g.idChan:
		return id
	default:
		// Channel is empty, generate a new UUID on the spot as fallback
		return generateUUID()
	}
}

// maxTraceIDLength bounds inbound X-Trace-ID values; generated IDs are 32 hex
// characters, and common formats (UUID, W3C trace IDs) fit comfortably below this.
const maxTraceIDLength = 64

// isValidTraceID reports whether an inbound X-Trace-ID header value is safe to
// propagate into logs and response headers. Only ASCII alphanumerics, '-', and
// '_' are allowed, with a bounded length, so clients can't inject log content
// or oversized values.
func isValidTraceID(id string) bool {
	if id == "" || len(id) > maxTraceIDLength {
		return false
	}
	for i := 0; i < len(id); i++ {
		c := id[i]
		switch {
		case c >= '0' && c <= '9':
		case c >= 'a' && c <= 'z':
		case c >= 'A' && c <= 'Z':
		case c == '-' || c == '_':
		default:
			return false
		}
	}
	return true
}

// CreateTraceMiddleware creates middleware that reuses a valid inbound
// X-Trace-ID or generates a new ID, stores it in the SRouter context, and sets
// the response X-Trace-ID header. Inbound IDs are limited to 64 ASCII letters,
// digits, hyphens, or underscores; invalid values are replaced. generator must
// be non-nil.
func CreateTraceMiddleware[T comparable, U any](generator *IDGenerator) common.Middleware {
	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			var traceID string

			// Check if there's already a valid trace ID in the request headers
			existingTraceID := r.Header.Get("X-Trace-ID")
			if isValidTraceID(existingTraceID) {
				// Use the existing trace ID for propagation
				traceID = existingTraceID
			} else {
				// Generate a new trace ID if none exists (or it was invalid)
				traceID = generator.GetIDNonBlocking()
			}

			// When an SRouterContext already exists (always the case inside the
			// router, which installs it before dispatch), WithTraceID mutates it
			// in place and returns the same context, so cloning the request is
			// unnecessary.
			_, hadSRouterCtx := scontext.GetSRouterContext[T, U](r.Context())

			// Add the trace ID to the request context using the correct generic types
			ctx := scontext.WithTraceID[T, U](r.Context(), traceID)

			// Add trace ID to the headers for logging or tracing
			w.Header().Set("X-Trace-ID", traceID)

			// Call the next handler with the request containing the updated context
			if !hadSRouterCtx {
				r = r.WithContext(ctx)
			}
			next.ServeHTTP(w, r)
		})
	}
}
