// Package logkeys defines the canonical structured-log field names emitted by
// SRouter. Applications can use the same keys to keep their logs aligned with
// the router without depending on a particular logging implementation.
package logkeys

const (
	Actual            = "actual"
	AuthTokenSource   = "auth_token_source"
	Bucket            = "bucket"
	BuildID           = "build_id"
	Bytes             = "bytes"
	ClampedValue      = "clamped_value"
	ClientIP          = "client_ip"
	ConfigID          = "config_id"
	Duration          = "duration"
	Error             = "error"
	Expected          = "expected"
	Fallback          = "fallback"
	HeaderName        = "header_name"
	Invariant         = "invariant"
	InvalidStatusCode = "invalid_status_code"
	IP                = "ip"
	Key               = "key"
	Limit             = "limit"
	Method            = "method"
	Methods           = "methods"
	MetricName        = "metric_name"
	Operation         = "operation"
	OriginalMessage   = "original_message"
	OriginalStatus    = "original_status"
	Panic             = "panic"
	Path              = "path"
	ProvidedBuckets   = "provided_buckets"
	Reason            = "reason"
	Remaining         = "remaining"
	RemoteAddr        = "remote_addr"
	ResetDuration     = "reset_duration"
	RetryAfterSeconds = "retry_after_seconds"
	Stack             = "stack"
	Stage             = "stage"
	Status            = "status"
	StatusCode        = "status_code"
	Strategy          = "strategy"
	Timeout           = "timeout"
	TraceID           = "trace_id"
	UserAgent         = "user_agent"
	UserID            = "user_id"
	Window            = "window"
)
